import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    './storage/framework/views/*.php',
    './resources/views/**/*.blade.php',
    './resources/js/**/*.js',
  ],

  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#2b29bb',
        'on-primary': '#472a00',
        'primary-fixed-dim': '#ffb95f',
        'on-secondary-fixed-variant': '#910030',
        'background': '#0c1322',
        'on-primary-fixed': '#2a1700',
        'surface-dim': '#0c1322',
        'surface-container-high': '#232a3a',
        'secondary-container': '#d4004b',
        'surface-variant': '#2e3545',
        'tertiary': '#c7c8ff',
        'error-container': '#93000a',
        'tertiary-container': '#a7a9ff',
        'on-primary-container': '#613b00',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#07006c',
        'primary-container': '#f59e0b',
        'primary': '#ffc174',
        'tertiary-fixed-dim': '#c0c1ff',
        'secondary': '#ffb2ba',
        'surface-bright': '#323949',
        'secondary-fixed-dim': '#ffb2ba',
        'inverse-surface': '#dce2f7',
        'on-secondary': '#670020',
        'on-secondary-fixed': '#400011',
        'on-secondary-container': '#ffe6e8',
        'outline': '#a08e7a',
        'on-primary-fixed-variant': '#653e00',
        'inverse-on-surface': '#293040',
        'surface-tint': '#ffb95f',
        'tertiary-fixed': '#e1e0ff',
        'secondary-fixed': '#ffd9dc',
        'surface-container-lowest': '#070e1d',
        'error': '#ffb4ab',
        'outline-variant': '#534434',
        'on-surface-variant': '#d8c3ad',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'on-surface': '#dce2f7',
        'surface-container-highest': '#2e3545',
        'surface': '#0c1322',
        'primary-fixed': '#ffddb8',
        'on-tertiary': '#1000a9',
        'on-background': '#dce2f7',
        'inverse-primary': '#855300',
        'on-error': '#690005',
        'surface-container-low': '#141b2b',
        'surface-container': '#191f2f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.25rem',
        'gutter-mobile': '0.75rem',
        'margin': '2rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        sans: ['Work Sans', ...defaultTheme.fontFamily.sans],
        'body-lg': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'body-sm': ['Work Sans', 'sans-serif'],
        'label-lg': ['Work Sans', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
      },
    },
  },

  plugins: [forms],
};

